version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    environment:
      - POSTGRES_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TTL_MINUTES=${JWT_TTL_MINUTES}
    command: ["fastapi", "run", "app/main.py", "--port", "8080"]
    container_name: backend
    depends_on:
      migrations:
        condition: service_completed_successfully

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://localhost:${API_PORT} # This environment variable is used in the frontend Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    container_name: frontend
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db_migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]

  migrations:
    image: postgres:13
    volumes:
      - ./backend/db_migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      bash -c "
      export PGPASSWORD=$POSTGRES_PASSWORD;
      until pg_isready -h db -U $POSTGRES_USER; do echo waiting for db; sleep 2; done;
      for f in /docker-entrypoint-initdb.d/*.sql; do
        echo running $$f;
        psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -f $$f;
      done"
    container_name: migrations

volumes:
  postgres_data:

