version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/code
    environment:
      - POSTGRES_DSN=postgresql://postgres:mysecretpassword@db/hu
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: hu
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db_migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

volumes:
  postgres_data:

