name: CI
on: [push, pull_request]
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint and Format Checks
        run: |
          make ruff_check
          make jslint
          make jsprettier-check

      - name: Backend unit tests
        run: make test_backend

      - name: Start frontend, backend and database
        run: make deploy

      - name: Integration tests with database
        run: make test_backend_integration

      - name: Install Playwright Browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run e2e tests with Playwright
        run: make test_e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
